authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]

[workspace]
projects = ["docs", "NotebookManagementTools"]

[deps]
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[compat]
MbedTLS_jll = "~2.28.0"
julia = "1.12"
