name = "MLJTutorial"
uuid = "1abb19d6-4667-4abd-b4d8-7a8f4bff7f54"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
IJulia = "1.23"
Pluto = "0.17, 0.18"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
