name = "MLJTutorial"
uuid = "1abb19d6-4667-4abd-b4d8-7a8f4bff7f54"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.0"

[workspace]
projects = ["docs", "NotebookManagementTools"]

[compat]
julia = "1.12"