version = "0.1.0"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]

[workspace]
projects = ["docs", "NotebookManagementTools"]

[deps]
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
MbedTLS_jll = "~2.28.0"
OrderedCollections = "1"
julia = "1.12"
