name: Test and Generate Notebooks as Needed
env:
  ACTIONS_STEP_DEBUG: true
  NOTEBOOK_ROOT: docs/src/notebooks/
on:
  pull_request:

jobs:
  generate_notebooks:
    # exclude pull request's spawned by this job; see "create-pull-request" below:
    if: |
      (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'auto-update-notebooks')) ||
      (github.event_name == 'push' && !startsWith(github.ref_name, 'auto-update-notebooks'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # get entire commit history, needed for changed-files to work

      - name: Get relevent changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            projects:
              - "**/Project.toml"
            notebooks:
              - "${{ env.NOTEBOOK_ROOT }}**"

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: 'min'

      - name: Enable caching
        uses: julia-actions/cache@v3

      - name: Julia package environment - instantiate and build
        uses: julia-actions/julia-buildpkg@v1
        
      - name: Identify, test, and generate notebooks
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate("NotebookManagementTools")
          import NotebookManagementTools
          
          workspace_changed =
              "${{ steps.changed-files.outputs.projects_any_changed }}" == "true"
          changed_notebook_files =
              split("${{ steps.changed-files.outputs.notebooks_all_changed_files }}", " ")

          # Path to directory where notebook subfolders live
          notebook_root = "${{ env.NOTEBOOK_ROOT }}"

          # Construct a list of dirs for notebooks needing regeneration
          notebook_dirs = workspace_changed ? 
              NotebookManagementTools.dirs(root=notebook_root) :
              NotebookManagementTools.dirs_containing(changed_notebook_files; root=notebook_root)

          # Test and generate the notebooks:
          markdown_files = NotebookManagementTools.generate(notebook_dirs; tests=true)

          if isnothing(markdown_files)
              @error "Problem testing a notebook or generating its markdown"
              exit(1)
          else 
              @info "Successfully re-generated these markdown files:\n "*
                  "$markdown_files "
          end 

      - name: Create pull request for adding new notebook markdown
        id: spawn_pr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update notebook markdown"
          branch: auto-update-notebooks
          base: ${{ github.base_ref }}
          title: "Commit Notebook Markdown Changes"
          body: |
            This pull request was automatically generated by \#${{ github.event.pull_request.number }} to update regenerated
            notebook markdown files.

            **Instructions**

            **Accept the invitation to run pending workflows.** If none are apparent, then
            close and immediately re-open this pull request. This will commit the new
            markdown and regenerate documentation.  If successful, merge this pull request
            to trigger deployment of the new docs to gh-pages.

            You can check repository "Actions" to check when deployment is complete.
            You should see: ✅ **pages build and deployment**

            This pull request will automatically update if additional commits are successfully
            added to the parent pull request, \#${{ github.event.pull_request.number }}.

          delete-branch: true
          add-paths: |
            **/notebook.md

      - name: Post comment flagging further action required
        if: steps.spawn_pr.outputs.pull-request-operation == 'created'
        uses: mshick/add-pr-comment@v3
        with:
          message: |
            **Attention**
            
            A notebook or Project.toml file has changed and new notebook 
            markdown has been generated. After merging this pull request, review \#${{ steps.spawn_pr.outputs.pull-request-number }}
            to commit the changes and update the documentation on gh-pages, as this will
            need to be regenerated.

